project_name: github-label-syncer
version: 2

env:
  - COSIGN_YES=true

# Prevents parallel builds from stepping on eachothers toes downloading modules
before:
  hooks:
    - go mod tidy
    - /bin/bash -c 'if [ -n "$(git --no-pager diff --exit-code go.mod go.sum)" ]; then exit 1; fi'

sboms:
  - artifacts: binary

builds:
  - id: github-label-syncer
    binary: github-label-syncer-{{ .Os }}-{{ .Arch }}
    no_unique_dist_dir: true
    main: .
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'

kos:
  - repository: ghcr.io/cpanato/github-label-syncer
    tags:
      - "{{.Version}}"
      - latest
    bare: true
    preserve_import_paths: false
    base_image: cgr.dev/chainguard/static:latest
    platforms:
      - linux/amd64
      - linux/arm64

signs:
  # Keyless
  - id: keyless
    signature: "${artifact}-keyless.sig"
    certificate: "${artifact}-keyless.pem"
    cmd: cosign
    args: ["sign-blob", "--output-signature", "${artifact}-keyless.sig", "--output-certificate", "${artifact}-keyless.pem", "${artifact}"]
    artifacts: binary
  - id: checksum-keyless
    signature: "${artifact}-keyless.sig"
    certificate: "${artifact}-keyless.pem"
    cmd: cosign
    args: ["sign-blob", "--output-signature", "${artifact}-keyless.sig", "--output-certificate", "${artifact}-keyless.pem", "${artifact}"]
    artifacts: checksum

archives:
  - format: binary
    name_template: "{{ .Binary }}"
    allow_different_binary_count: true

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: SNAPSHOT-{{ .ShortCommit }}

release:
  prerelease: auto
  draft: true # allow for manual edits
  github:
    owner: cpanato
    name: github-label-syncer
